spring.mail.host=localhost
spring.mail.port=25
management.health.mail.enabled=false

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.caffeine.acs_backend=DEBUG

server.error.include-stacktrace=always