name: Lint and Format Check

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ] # Trigger only on PRs targeting main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      # Skip three formatting/linting related steps
      skip_linting:
        description: 'Skip Java and Dockerfile linting? (true/false)'
        default: 'false'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check Java Formatting
        if: github.event.inputs.skip_linting != 'true'
        run: ./gradlew spotlessCheck

      - name: Check Linting (Static Analysis)
        if: github.event.inputs.skip_linting != 'true'
        run: ./gradlew checkstyleMain

      - name: Lint Dockerfiles
        if: github.event.inputs.skip_linting != 'true'
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "**/Dockerfile*"
          recursive: true
